services:
  - type: web
    name: api-s-youtube
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
      pip install yt-dlp
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8